helloworld controller
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #11
Opened 2022-01-12 10:52 UTC by Anastas0v

2022-01-12 15:19 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-12 15:19 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/HelloController.java
> +    @GetMapping("/helloworld")
By convention, we should use **hyphenated style** when naming routes, instead of `/HelloWorld` change it to `/hello-world`

2022-01-12 15:19 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/HelloController.java
> +    public String helloworld()
By convention, we should use **camelCase** for java method naming , instead of `helloworld` change it to `helloWorld`

2022-01-13 08:17 UTC, dejannastevski-armedia approved these changes

2022-01-13 13:17 UTC, aleksandar-bujaroski-armedia approved these changes

2022-01-13 13:17 UTC, merged