Hello commit
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #12
Opened 2022-01-12 11:02 UTC by marijamitreska

2022-01-12 15:23 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-12 15:23 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/main/java/com/example/demo/controller/HelloController.java
> +public class HelloController {
Please fix the formatting, in Armedia projects we're using this code style:
BAD CODE FORMATTING: 
```
@RestController
public class HelloController {
    @RequestMapping("/")
    String index() {
        return "Hello, World!";
    }
} 
```

GOOD CODE FORMATTING:
```
@RestController
public class HelloController 
{
    @RequestMapping("/")
    String index() 
    {
        return "Hello, World!";
    }
} 
```

2022-01-12 15:23 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/main/java/com/example/demo/DemoApplication.java
> +        SpringApplication.run(DemoApplication.class, args);
Same here, change the formatting

2022-01-13 09:55 UTC, dejannastevski-armedia approved these changes

2022-01-13 09:55 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/DemoApplication.java
> +            SpringApplication.run(DemoApplication.class, args);
Please do the formatting changes here as well.

2022-01-13 17:19 UTC, merged