initial commit
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #14
Opened 2022-01-13 13:10 UTC by Anastas0v

2022-01-14 15:15 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-14 15:15 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/pom.xml
> +			<version>4.3.1</version>
Extract version number <version>4.3.1</version> to variable at the top of the file:
Example:
```
   <properties>
        <bootstrap.version>4.3.1</bootstrap.version>
   </properties>

```
Then use it in this way:
`<version>${bootstrap.version}</version>`

2022-01-14 15:15 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +public class RegisterController
You should add initial route for this Controller after @Controller annotation:
Example:
`@RequestMapping(value = "/auth")`

2022-01-14 15:15 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +        if(userName.isEmpty() || userName.length() <= 2)
null check missing

2022-01-17 08:19 UTC, dejannastevski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +    @GetMapping("/register/registerPage")
Minor: change this to register-page

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/pom.xml
> +			<version>3.4.1</version>
You should extract this version to variable

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/pom.xml
> +			<version>5.6.1</version>
This one too

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/models/User.java
> +package com.example.firstproject.models;
Package name should be singular -> **models** vs **model**

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationService.java
> +    String validate(User user);
Change method name to be more descriptive.
Example: validateUserRegistrationInfo

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +public class AuthenticationServiceImpl implements AuthenticationService {
Fix code formatting

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +        User newUser = new User();
This create whole new user object, change method name to reflect method logic

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/util/PasswordHashing.java
> +    public PasswordEncoder encoder() {
Change code formatting

2022-01-17 13:01 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +public class RegisterController
Change controller name to **AuthController** if you'll use this controller for login too

2022-01-17 13:10 UTC, Anastas0v commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +public class RegisterController
i want to make another controller for login

2022-01-17 13:49 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-17 13:49 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +public class RegisterController
Then change the **@RequestMapping(value = "/auth")** to **@RequestMapping(value = "/register")** and remove **register** from route name

2022-01-17 13:49 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/RegisterController.java
> +    @GetMapping("/login")
Remove login if you create new controller

2022-01-17 13:49 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/AuthenticationController.java
> +@RequestMapping(value = "/auth")
Change the route to be **@RequestMapping(value = "/register")** if you create new controller for login and remove register from other routes names:
Example:  `@GetMapping("/register/register-page")` to ` @GetMapping("/register-page")`

2022-01-17 13:49 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/controller/AuthenticationController.java
> +    @GetMapping("/login")
Remove login if you create new login controller

2022-01-17 14:14 UTC, aleksandar-bujaroski-armedia approved these changes

2022-01-17 14:14 UTC, dejannastevski-armedia approved these changes

2022-01-17 14:19 UTC, merged