Novica veljanoski register user
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #16
Opened 2022-01-13 13:37 UTC by 173038

2022-01-13 14:44 UTC, dejannastevski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AppController.java
> +public class AppController
Change to AuthenticationController

2022-01-13 14:45 UTC, dejannastevski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AppController.java
> +public class AppController
Add corresponding mapping for this controller

2022-01-13 14:50 UTC, dejannastevski-armedia commented
Add service layer and corresponding logic for user registration in it.

2022-01-17 08:22 UTC, dejannastevski-armedia commented on project-novica/demo/pom.xml
> +			<version>4.3.1</version>
Extract version number 4.3.1 to variable at the top of the file:
Example:

   <properties>
        <bootstrap.version>4.3.1</bootstrap.version>
   </properties>

Then use it in this way:
<version>${bootstrap.version}</version>

2022-01-17 08:22 UTC, dejannastevski-armedia commented on project-novica/demo/pom.xml
> +			<version>3.4.1</version>
Same here

2022-01-17 08:23 UTC, dejannastevski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +//    @PostMapping("/register")
Remove commented code if its not needed.

2022-01-17 08:25 UTC, dejannastevski-armedia commented on project-novica/demo/src/main/java/com/example/demo/model/exceptions/InvalidargumentException.java
> +public class InvalidargumentException extends Throwable {
Change to InvalidArgumentException

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/pom.xml
> +			<version>3.4.1</version>
Extract version number 4.3.1 to variable at the top of the file:
Example:

```
   <properties>
        <bootstrap.version>4.3.1</bootstrap.version>
   </properties>
```

Then use it in this way:
`<version>${bootstrap.version}</version>`

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +    public String viewHomePage(Model model)
Why do we have the main application route added in the AuthenticationController ?

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/model/exceptions/InvalidargumentException.java
> +public class InvalidargumentException extends Throwable {
fix the code format:
We're following the following code style:
```
public interface AuthenticationService 
{
}
```
This should apply to all methods and classes

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/service/impl/AuthenticationServiceImpl.java
> +   private UserRepository userRepository;
How is this working without @Autowired annotation ?

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/service/impl/AuthenticationServiceImpl.java
> +   private UserRepository userRepository;
You're using construction injection, but you should use field injection:
Example of constructor injection:
```
@Autowired
    public AuthenticationServiceImpl(UserRepository userRepository){
        this.userRepository=userRepository;
    }
```

Example of field injection:
```
@Autowired
private UserRepository userRepository;
```

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/service/impl/AuthenticationServiceImpl.java
> +    public boolean checkPassword(String password) {
What if password isEmpty or null ?

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/pom.xml
> +			<version>5.6.1</version>
Extract this version to variable

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +public class AuthenticationController
Add default mapping for this controller:
Example:
@RequestMapping(value = "/auth")

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +
Extract business logic to service

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +    public String deleteUser(@PathVariable Long id)
This is not needed for this ticket, also, this is not belonging to AuthenticationController

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +        List<User>listUsers=authenticationService.getAllUsers();
This is not needed for this ticket, also, this is not belonging to AuthenticationController

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/model/exceptions/EmailAlreadyExistException.java
> +    public EmailAlreadyExistException(String message){
Fix code formatting

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/model/exceptions/InvalidArgumentException.java
> +    {
Fix code formatting

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/service/AuthenticationService.java
> +    boolean checkUserName(String firstName);
Refactor this method, so that every method in the authentication service is only used for authentication purposes

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/service/impl/AuthenticationServiceImpl.java
> +        User user1=this.userRepository.getById(id);
Rename **user1** variable to **userToBeUpdated**

2022-01-17 13:08 UTC, aleksandar-bujaroski-armedia commented on project-novica/demo/src/main/java/com/example/demo/util/PasswordHashing.java
> +    public PasswordEncoder encoder(){
Fix code formatting

2022-01-18 09:52 UTC, merged