Register
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #22
Opened 2022-01-13 17:30 UTC by marijamitreska

2022-01-14 08:10 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/model/User.java
> +    @Table(name = "userregister")
We need this table for saving users, so this table should be named "user" instead.

2022-01-14 08:12 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/model/authenticationController.java
> +    public class authenticationController
By convention class name always starts with capital letter. Object names and variable names start with small letter.

2022-01-14 08:14 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/model/authenticationController.java
> +        @GetMapping(" ")
Remove the empty space in the @GetMapping if you want that to be default mapping value.

2022-01-14 08:14 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/model/authenticationController.java
> +        @PostMapping("/process_register")
Change to "/process-register" instead.

2022-01-14 13:40 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-14 13:40 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/main/java/com/example/demo/model/UserRepository.java
> +    package com.example.demo.model;
UserRepository should be in separate repository directory in order to follow MVC model

2022-01-14 13:40 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/main/java/com/example/demo/model/authenticationController.java
> +    package com.example.demo.model;
AuthenticationController should be in separate controller directory in order to follow MVC model

2022-01-14 13:40 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/main/java/com/example/demo/model/authenticationController.java
> +        private UserRepository userRepo;
Refactor the code and extract business logic to Service

2022-01-14 13:40 UTC, aleksandar-bujaroski-armedia commented on Project/demo/src/test/java/com/example/demo/UserRepositoryTest.java
> +    package com.example.demo;
Add this test code to separate directory called test

2022-01-14 13:43 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-14 13:43 UTC, aleksandar-bujaroski-armedia commented on Project/demo/pom.xml
> +		<version>4.3.1</version>
Extract version number <version>4.3.1</version> to variable at the top of the file:
Example:
   <properties>
        <bootstrap.version>4.3.1</bootstrap.version>
   </properties>
Then use it in this way:
<version>${bootstrap.version}</version>

2022-01-17 15:18 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/controller/AuthenticationController.java
> +
Remove these empty lines.

2022-01-17 15:18 UTC, dejannastevski-armedia commented on Project/demo/src/main/java/com/example/demo/controller/HelloController.java
> +//        package com.example.demo.controller;
remove commented code.

2022-01-18 10:10 UTC, merged