Login User
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #25
Opened 2022-01-20 15:10 UTC by Anastas0v

2022-01-20 15:24 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-20 15:24 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/FirstprojectApplication.java
> +}
This is not an actual change, so you should remove it

2022-01-20 15:24 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/resources/templates/login.html
> +    function submit(){
Extract the function to separate js file

2022-01-20 16:21 UTC, aleksandar-bujaroski-sharecare requested changes

2022-01-20 16:21 UTC, aleksandar-bujaroski-sharecare commented on project/firstproject/src/main/java/com/example/firstproject/FirstprojectApplication.java
> +}
The code change is still here reported as change

2022-01-20 16:21 UTC, aleksandar-bujaroski-sharecare commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +    public String loginUser(String email, String password) {
Method opening {, should be in new line

2022-01-20 16:21 UTC, aleksandar-bujaroski-sharecare commented on project/firstproject/src/main/resources/static/javascript/scripts.js
> +function submit()
Change script name to reflect it's functionality. 
Example: loginUtils

2022-01-20 16:21 UTC, aleksandar-bujaroski-sharecare commented on project/firstproject/src/main/resources/static/javascript/scripts.js
> +    var userdto = {};
Change variable name from `userdto` to `userDTO`

2022-01-21 08:44 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-21 08:44 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +    public String loginUser(String email, String password) {
Fix code formatting

2022-01-21 08:44 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/FirstprojectApplication.java
> +}
The change is still here

2022-01-21 08:44 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/resources/static/javascript/scripts.js
> +function submit()
Rename this file to reflect it's logic.
Example: loginUtils.js

2022-01-21 08:44 UTC, aleksandar-bujaroski-armedia commented on project/firstproject/src/main/java/com/example/firstproject/services/AuthenticationServiceImpl.java
> +                else
This should be changed to `else if` block because there is only one check:
` else if(!passwordEncoder.matches(password,dbUser.getPassword()))`

2022-01-21 11:31 UTC, aleksandar-bujaroski-armedia approved these changes

2022-01-21 11:41 UTC, dejannastevski-armedia approved these changes

2022-01-21 11:41 UTC, merged