Hello World
dejannastevski-armedia/ArmediaMK-2022-Winter-Internship-Project pull request #9
Opened 2022-01-12 10:51 UTC by HristijanSlavkoski

2022-01-12 15:14 UTC, aleksandar-bujaroski-armedia requested changes

2022-01-12 15:14 UTC, aleksandar-bujaroski-armedia commented on project/First-Project/src/main/java/first/project/controller/HelloController.java
> +    @RequestMapping(value = "/HelloWorld", method = RequestMethod.GET)
By convention, we should use **hyphenated** style when naming routes, instead of `/HelloWorld` change it to `/hello-world`

2022-01-12 16:08 UTC, aleksandar-bujaroski-sharecare approved these changes

2022-01-12 17:27 UTC, aleksandar-bujaroski-armedia approved these changes

2022-01-13 08:17 UTC, dejannastevski-armedia approved these changes

2022-01-13 13:12 UTC, merged